### ISSUE TITLE
[BUG]  1.12.2 doesn't work.   Nothing from Cleanse shows up in the latest.log, either.

### ISSUE THREAD

**Issue by ghost** [necauqua/Cleanse#1] opened 2021-12-30 21:28 UTC
Hi there. I have Cleanse 1.12.2 - 1.0.1.0.

`[Cleanse]: Reenabled adding new chat lines` never shows up in the latest.log file. In fact, I don't see Cleanse doing anything in the latest log at all.

I would happily pay you for your time to see if you can get this working! This is the only mod of its kind out there.

**Comment by necauqua** [comment] 2021-12-30 21:33
Huh, I am assuming you did put the jar in the client mods folder with forge installed.

Does `cleanse` show up at all in `latest.log`?
Would appreciate if you just send it also (ugh I did not set up issue templates for cleanse where I ask to attach the file)

**Comment by ghost** [comment] 2021-12-30 21:38
Yes, it is of course in the `mods` folder.

[latest.log](https://github.com/necauqua/Cleanse/files/7794692/latest.log)

Cleanse does show up. It does the version check, but nothing beyond that.

**Comment by necauqua** [comment] 2021-12-30 22:00
Ok im looking into is, takes a while to fight gradle to setup the 1.12 workspace

Meanwhile if this is a public modpack can you share the name, or DM me (in discord) an archive, because hopefully I didn't put out a version that plain does not work :) I always check at least if the line shows up in logs, but don't remember if I did so for 1.12 lul

**Comment by ghost** [comment] 2021-12-30 22:09
So I just tested a small "test modpack" with Cleanse, and a few mods that I know paste their text on worldjoin.
Cleanse worked in this example perfectly. Nothing showed in the latest.log, however, except the versioncheck.

So, I don't think the 1.12.2 version adds anything to the latest.log, but it still functions in a small modpack.

That means, there is something in this modpack of mine that is preventing Cleanse from working? Not sure why that would be the case. I've set the ticks to 25 seconds (500 ticks) and it always shows the text on join.

What's your discord? I'll see about sending a copy of the modpack.

Here's a trailer: https://www.youtube.com/watch?v=X8EpwHdR62k&ab_channel=Finecraft%3AEnhancedSurvival
Here's the Wiki: https://github.com/roccscout/Finecraft/wiki

**Comment by necauqua** [comment] 2021-12-31 02:46
Ok after spending a lot of time I've came to the conclusion that it's impossible to run 1.12 on NixOS, omg
Or at least pretty hard, ugh

I actually have an idea of what may cause this - you must have a mod that changes the main menu?
I can see how that can potentially break cleanse (I detect the `main-menu -> world` transition to start the timer and `anything -> main menu` to reset it)

The discord is [this](https://discord.necauqua.dev), you can also ask for help (about my mods anyway) from people there :)

**Comment by necauqua** [comment] 2021-12-31 04:01
It was indeed caused by Custom Main Menu mod, closed in 5cc9bac

**Closed as completed by necauqua** 2021-12-31 04:01 UTC
